security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        api:
            id: App\Security\Provider\ApiProvider

    role_hierarchy:
        ROLE_SUPER_ADMIN:  [ROLE_ADMIN]
        ROLE_ADMIN: ROLE_USER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        app_version:
            pattern: ^/state$
            security: false
        
        default:
            pattern: ^/default$
            security: false

        login:
            pattern:  ^/login$
            security: false
            guard:
                authenticators:
                    - App\Security\Authenticator\LoginFormAuthenticator

        register:
            pattern:  ^/register
            security: false

        main:
            pattern: ^/
            security: true
            switch_user: true
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /
                use_forward: true
                username_parameter: username
                password_parameter: password
            logout:
                path:   /logout
                target: /login
            guard:
                authenticators:
                    - App\Security\Authenticator\ConfirmEmailAuthenticator
                    - App\Security\Authenticator\LoginFormAuthenticator
                entry_point: App\Security\Authenticator\ConfirmEmailAuthenticator
    access_control:
        - { path: ^/, roles: ROLE_USER }
