twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'components/form.html.twig'
    globals:
        # recaptcha_site_key: '%env(RECAPTCHA_CLIENT_KEY)%'
        version: '%env(APP_VERSION)%'
    paths:
        '%kernel.project_dir%/public/build/css': css
